export const SOMETHING_WENT_WRONG = "Something went wrong while fetching the resource";
export const FAILED_TO_DELETE_USER = "Failed to delete user";
export const USER_CREATED = "User created";
export const USER_DELETED = "User Deleted";
export const USER_DOES_NOT_FOUND = "User doesn't exists";
export const LOGGED_IN_SUCCESS= "Logged in successfully"
export const UNAUTHORIZED_ERROR = "Unauthorized"
export const VERIFIED_SUCCESS = "User Verify"
export const FAILED_TO_VERIFY = "Failed to verify user"